### ISSUE TITLE
Epic: Article Category

### ISSUE THREAD

**Issue by lynnbright** [lynnbright/MyBlog#7]
### Epic Description

- [ ] Admin can add multiple categories to single article
- [ ] User can click single category tag and browse articles which have the tag
- [ ] User can see the number of articles on each category tag
